trigger: none
pool: vmss_agent

- stage: lintingstage
  displayName: codequalitychecks
  jobs: 
  - job: biomelint
    displayName: biomelint
    steps:
    - task: PowerShell@2
      displayName: javascipt linter
      continueOnError: true
      inputs:
        targetType: 'inline'
        script: |
          Invoke-WebRequest -Uri "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%402.3.8/biome-win32-x64.exe" -OutFile "$(Agent.ToolsDirectory)/biome.exe"
          $(Agent.ToolsDirectory)/biome.exe lint $(System.DefaultWorkingDirectory)/src